baseURL: "http://example.org/"
languageCode: "ja-jp"
title: 'Hugoでテーマを自作する'
contentDir: "content"
hasCJKLanguage: true

copyright: "(c) 2022-{year} Harapeco Ito"

disableKinds:
  - "RSS"
  - "sitemap"

permalinks:
  blog: /blog/:year:month:day/:filename/
  item: /item/:year:month:day/:filename/

markup:
  goldmark:
    renderer:
      unsafe: true

