author:
  companyname: "おなかをすかせた"
  name: "伊藤昭浩"
  twitter: "https://twitter.com/panda2taro"
  tags:
    - アスペルガー症候群
    - 注意欠陥多動性障害
    - 双極性障害
    - 睡眠障害
    - 睡眠時無呼吸症候群
    - 甲状腺腫（良性・手術済）
    - 低体温（34.6℃）
    - 企図振戦
    - 慢性咳嗽
    - 自動車運転禁止

